# DSC 478
## Daniel O'Brien

## Homework 3 Part 2
#### Part a

In [2]:
import numpy as np
import pandas as pd

In [5]:
# TermDocument is how it is arranged
TD = np.loadtxt('matrix.txt', delimiter=',')
#matrix

In [6]:
TD.shape

(9328, 2500)

In [7]:
# We transpose it to get document by term and now we will work with DT
DT = TD.T

In [8]:
classes = pd.read_table('/Users/danielobrien/cluster/classes.txt', index_col=0, sep = ' ', skiprows=1, header=None)
#classes

In [80]:
terms = pd.read_table('/Users/danielobrien/cluster/terms.txt', header =None)
terms

0
0         aa
1      aargh
2      aaron
3     aaronc
4         ab
...      ...
9323   zubov
9324      zv
9325      zw
9326      zx
9327      zz

[9328 rows x 1 columns]

In [10]:
print(terms.shape)

(9328, 1)


In [11]:
print(classes.shape)

(2500, 1)


In [12]:
classes.shape

(2500, 1)

In [13]:
###number of terms - train data set
print(DT.shape)
numTerms = DT.shape[1]
print (numTerms)

(2500, 9328)
9328


In [14]:
###number of documents - train data set
NDocs = DT.shape[0]
print (NDocs)

2500


In [15]:
# I had missed this earlier - I could not spot an error but you want to do array manipulation 
# in numpy and not with frames. Frames are good for printing, cleaning etc.
#DT = pd.DataFrame(matrixT, columns=terms)
#matrixDT

In [16]:
#DT.shape
###document freqs for each term
DF = np.array([(DT!=0).sum(0)])
print (DF[:10])
print (DF.shape)
#check for null DFs - There are no nulls it seems like
print (np.unique([DF==0]))

[[10  6 22 ...  3  3  4]]
(1, 9328)
[False]


#### Part b

In [18]:
from sklearn.model_selection import train_test_split
#matrix2, x_test, y_train, y_test = train_test_split(matrix1, classes, test_size=0.2, random_state=35)

#from sklearn.model_selection import train_test_split
DT_train, DT_test, y_train, y_test = train_test_split(DT, classes, test_size=0.2, random_state=35)


#DT = matrix2
#print (DT_train[:10])

In [19]:
numTerms=DT_train.shape[1]

In [20]:
NDocs = DT_train.shape[0]

In [21]:
numTerms

9328

In [22]:
NDocs

2000

In [23]:
#termFreqs = DT.sum(axis=0)
#termFreqs.shape

In [24]:
###document freqs for each term
#DF = np.array([(DT_train!=0).sum(0)])


In [25]:
#DF
#NDocs

In [26]:
# Create a matrix with all entries = NDocs
###matrix with all entries = NDocs
NMatrix = np.ones(np.shape(DT_train),dtype=float)*NDocs
print (NMatrix.shape)
print (NMatrix[1:5,1:5])
#NMatrix=np.ones(np.shape(DT_train), dtype=float)*NDocs
#np.set_printoptions(precision=2,suppress=True,linewidth=120)
#print(NMatrix)

(2000, 9328)
[[2000. 2000. 2000. 2000.]
 [2000. 2000. 2000. 2000.]
 [2000. 2000. 2000. 2000.]
 [2000. 2000. 2000. 2000.]]


In [27]:
# Convert each entry into IDF values
# IDF is the log of the inverse of document frequency
# Note that IDF is only a function of the term, so all columns will be identical.

IDF = np.log2(np.divide(NMatrix,DF))
#IDF = np.log2(np.divide(NMatrix, np.array(DF)))
#IDF = np.log2(np.divide(NMatrix, np.array(DF)))


In [28]:
np.set_printoptions(precision=2,suppress=True)
print(IDF)

[[7.64 8.38 6.51 ... 9.38 9.38 8.97]
 [7.64 8.38 6.51 ... 9.38 9.38 8.97]
 [7.64 8.38 6.51 ... 9.38 9.38 8.97]
 ...
 [7.64 8.38 6.51 ... 9.38 9.38 8.97]
 [7.64 8.38 6.51 ... 9.38 9.38 8.97]
 [7.64 8.38 6.51 ... 9.38 9.38 8.97]]


In [29]:
# Finally compute the TFxIDF values for each document-term entry
#TD_tfidf = DT * IDF
DT_train_tfidf = DT_train*IDF
DT_test_tfidf = DT_test*IDF[:len(DT_test),:]
#DT_test_tfidf = np.multiply(IDF[:500,:],DT_test,tfidfTest) #apply IDF on test set
print (DT_train_tfidf.shape)
print (DT_test_tfidf.shape)


(2000, 9328)
(500, 9328)


In [30]:
#pd.set_option("display.precision", 2)

DT_train_tfidf
DT_train_tfidf_np = np.array(DT_train_tfidf)

In [31]:
#DT_test_tfidf

In [32]:

import kMeans
import importlib

In [33]:
importlib.reload(kMeans)

<module 'kMeans' from '/Users/danielobrien/cluster/kMeans.py'>

### Part c

In [34]:
#kMeans.randCent(TD_tfidf, 5)
centroids,clustersErr=kMeans.kMeans(DT_train_tfidf_np,distMeas=kMeans.distCosine,k=5)

In [35]:
def cluster_sizes(data):
    #clusters is an array of cluster labels for each instance in the data
    
    size = {}
    cluster_labels = np.unique(clusters)
    n_clusters = cluster_labels.shape[0]

    for c in cluster_labels:
        size[c] = len(data[clusters == c])
    return size

In [36]:
clusters=clustersErr[:,0]
size = cluster_sizes(clusters)
print(size)
#myCentroids, clustAssing = kMeans.kMeans(TD_tfidf, 5, distan)

{0.0: 2, 1.0: 769, 2.0: 392, 3.0: 828, 4.0: 9}


In [37]:
print (centroids)

[[0.   0.   0.   ... 0.   0.   0.  ]
 [0.02 0.   0.03 ... 0.   0.   0.  ]
 [0.02 0.   1.13 ... 0.   0.   0.  ]
 [0.07 0.05 0.01 ... 0.11 0.07 0.14]
 [0.   0.   0.   ... 1.04 0.   0.  ]]


In [49]:
print(clustersErr)

[[3.   0.76]
 [2.   0.81]
 [3.   0.84]
 ...
 [3.   0.64]
 [3.   0.86]
 [3.   0.78]]


In [42]:
clusters = pd.DataFrame(clustersErr, columns = ['Cluster','Dist'])
clusters

Cluster      Dist
0         3.0  0.755463
1         2.0  0.812010
2         3.0  0.837127
3         2.0  0.614018
4         2.0  0.588215
...       ...       ...
1995      1.0  0.858090
1996      1.0  0.906112
1997      3.0  0.640850
1998      3.0  0.863315
1999      3.0  0.778836

[2000 rows x 2 columns]

In [43]:
column1 = clusters.iloc[:, 0]
column1

0       3.0
1       2.0
2       3.0
3       2.0
4       2.0
       ... 
1995    1.0
1996    1.0
1997    3.0
1998    3.0
1999    3.0
Name: Cluster, Length: 2000, dtype: float64

In [44]:
column1 = np.array(column1)

In [45]:
unique = clusters['Cluster'].unique()
unique

array([3., 2., 1., 4., 0.])

In [50]:
size = {}
for c in unique:
    size[c] = len(DT_train_tfidf_np[column1 == c])
print(size)

{3.0: 828, 2.0: 392, 1.0: 769, 4.0: 9, 0.0: 2}


In [52]:
centroidsdf = pd.DataFrame(centroids, columns = terms)

centroidsdf

(aa,)  (aargh,)  (aaron,)  (aaronc,)     (ab,)  (abandon,)    (abc,)  \
0  0.000000  0.000000  0.000000   0.000000  0.000000    0.000000  0.000000   
1  0.019880  0.000000  0.033843   0.000000  0.047239    0.020275  0.015758   
2  0.019500  0.000000  1.128653   0.119324  0.037068    0.099437  0.000000   
3  0.073854  0.050609  0.007858   0.000000  0.140393    0.000000  0.314653   
4  0.000000  0.000000  0.000000   0.000000  0.807261    0.000000  0.000000   

    (abid,)   (abil,)    (abl,)  ...     (zq,)     (zr,)    (zrb,)      (zs,)  \
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   0.000000   
1  0.000000  0.107328  0.248549  ...  0.000000  0.000000  0.000000   0.000000   
2  0.023931  0.223707  0.361175  ...  0.000000  0.000000  0.000000   0.000000   
3  0.033988  0.193130  0.307784  ...  0.088679  0.156592  0.022659   0.070852   
4  0.000000  0.000000  0.000000  ...  0.000000  0.960428  0.000000  11.174429   

      (zu,)  (zubov,)     (zv,)     (zw,)     (zx,)     (zz,)  
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3  0.079306  0.060731  0.407138  0.113295  0.067977  0.140767  
4  0.000000  0.000000  0.000000  1.042314  0.000000  0.000000  

[5 rows x 9328 columns]

In [64]:
clustergroups = clusters.groupby(clusters.Cluster)


In [58]:
cluster3 = clustergroups.get_group(3)
cluster3

Cluster      Dist
0         3.0  0.755463
2         3.0  0.837127
9         3.0  0.726497
11        3.0  0.528637
12        3.0  0.717767
...       ...       ...
1993      3.0  0.899472
1994      3.0  0.743319
1997      3.0  0.640850
1998      3.0  0.863315
1999      3.0  0.778836

[828 rows x 2 columns]

In [59]:
cluster2 = clustergroups.get_group(2)
cluster2

Cluster      Dist
1         2.0  0.812010
3         2.0  0.614018
4         2.0  0.588215
5         2.0  0.681968
6         2.0  0.665114
...       ...       ...
1950      2.0  0.490555
1955      2.0  0.734878
1958      2.0  0.773009
1969      2.0  0.630835
1981      2.0  0.598840

[392 rows x 2 columns]

In [60]:
cluster1 = clustergroups.get_group(1)
cluster1

Cluster      Dist
7         1.0  0.606834
10        1.0  0.757923
13        1.0  0.857475
14        1.0  0.500462
17        1.0  0.649982
...       ...       ...
1980      1.0  0.580057
1987      1.0  0.851442
1988      1.0  0.670622
1995      1.0  0.858090
1996      1.0  0.906112

[769 rows x 2 columns]

In [61]:
cluster4 = clustergroups.get_group(4)
cluster4

Cluster          Dist
325       4.0  6.630234e-10
851       4.0  2.540824e-08
985       4.0  2.635512e-08
1123      4.0  4.450203e-10
1635      4.0  1.196080e-09
1649      4.0  8.989245e-01
1676      4.0  1.153019e-07
1694      4.0  6.343301e-01
1985      4.0  2.471013e-10

In [63]:
cluster0 = clustergroups.get_group(0)
cluster0

Cluster          Dist
1376      0.0  1.027516e-09
1572      0.0  6.329931e-01

In [74]:
cluster4Sort = cluster4.sort_values(by=['Dist'])
cluster4Sort.head(10)


Cluster          Dist
1985      4.0  2.471013e-10
1123      4.0  4.450203e-10
325       4.0  6.630234e-10
1635      4.0  1.196080e-09
851       4.0  2.540824e-08
985       4.0  2.635512e-08
1676      4.0  1.153019e-07
1694      4.0  6.343301e-01
1649      4.0  8.989245e-01

In [84]:
print("\nCluster ", 0, "size =", size[0])
print("----------------------------------------------")
for row in cluster0:
    cluster0sort = cluster0.sort_values(by=['Dist'])
    cluster0sort = cluster0sort.head(5)
    for index, row in cluster0sort.iterrows():
        #term = terms[index]
        print(row[1])

#print(cluster_rep.sort_values(by="DF", ascending=False).head(numTerms))



Cluster  0 size = 2
----------------------------------------------
1.0275156454747396e-09
0.6329931133010451
1.0275156454747396e-09
0.6329931133010451


In [87]:
print("\nCluster ", 1, "size =", size[1])
print("----------------------------------------------")
for row in cluster1:
    cluster1sort = cluster1.sort_values(by=['Dist'])
    cluster1sort = cluster1sort.head(5)
    for index, row in cluster1sort.iterrows():
        #term = terms[index]
        print(row[1])


Cluster  1 size = 769
----------------------------------------------
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417


In [88]:
print("\nCluster ", 2, "size =", size[2])
print("----------------------------------------------")
for row in cluster2:
    cluster2sort = cluster2.sort_values(by=['Dist'])
    cluster2sort = cluster2sort.head(5)
    for index, row in cluster1sort.iterrows():
        #term = terms[index]
        print(row[1])


Cluster  2 size = 392
----------------------------------------------
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417


In [89]:
print("\nCluster ", 3, "size =", size[3])
print("----------------------------------------------")
for row in cluster3:
    cluster3sort = cluster3.sort_values(by=['Dist'])
    cluster3sort = cluster3sort.head(5)
    for index, row in cluster1sort.iterrows():
        #term = terms[index]
        print(row[1])


Cluster  3 size = 828
----------------------------------------------
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417


In [90]:
print("\nCluster ", 4, "size =", size[4])
print("----------------------------------------------")
for row in cluster4:
    cluster4sort = cluster4.sort_values(by=['Dist'])
    cluster4sort = cluster4sort.head(5)
    for index, row in cluster1sort.iterrows():
        #term = terms[index]
        print(row[1])


Cluster  4 size = 9
----------------------------------------------
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417
0.3822462232805065
0.3912994395418948
0.41628464163880824
0.42010746423816664
0.42227023103131417


In [72]:
# for each cluster we need top n words, df(how many documents they appear in), and percentage of total documents in the cluster

## Part d
#### Completeness score measures whethers data points that are clustered together belong to the same class or not, a measure 1 indicates that all points that are clustered together are in the same class

#### Homogeneity measures whether clusters contain only members of a single class.  A homegeneity score of 1 indicates that clusters all contain members of single classes


In [91]:
from sklearn.metrics import completeness_score, homogeneity_score

In [92]:
newC = clusters["Cluster"].astype(int)


In [93]:
y_train = np.array(y_train).flatten()

In [94]:
print(completeness_score(y_train,newC))

0.7815094786147689


In [95]:
print(homogeneity_score(y_train,newC))

0.5260339273169974


## My completeness score is 0.78, which indicates that many of the some points that are clustered together do not belong to the same class, but overall many points of the same class are clusted together. And my homogeneity score of 0.53 shows that my clusters do not contain documents from a single class

### Part e

### Testing with my test set and producing the distance measures. I also ran the test set for homogeneity and completeness. The scores were both pretty low as well, which was not surprising to me based on the trouble I had with the training set.

In [100]:
myCentroids, clustAssing = kMeans.kMeans(DT_test, 5)

In [101]:
DT_train, DT_test, y_train, y_test

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([1, 2, 3, ..., 3, 2, 3]),
 array([0, 2, 0, 1, 4, 1, 2, 0, 3, 1, 1, 3, 4, 2, 4, 1, 0, 2, 0, 2, 0, 0,
        0, 2, 4, 1, 3, 1, 2, 3, 3, 0, 1, 2, 0, 1, 4, 1, 2, 3, 1, 4, 0, 2,
        3, 1, 2, 2, 2, 3, 0, 2, 1, 3, 3, 1, 4, 3, 2, 1, 2, 4, 0, 1, 4, 3,
        0, 2, 1, 0, 4, 4, 3, 1, 3, 2, 4, 4, 4, 0, 4, 0, 2, 4, 0, 3, 4, 1,
        4, 4, 3, 3, 4, 1, 4, 1, 3, 1, 3, 2, 0, 4, 4, 1, 2, 2, 4, 1, 4, 4,
        1, 3, 3, 1, 0, 1, 3, 1, 2, 0, 2, 1, 1, 1, 3, 2, 3, 2, 0, 2, 4, 1,
        1, 2, 0, 2, 3, 4,

In [102]:
print(myCentroids, clustAssing)

[[0.   0.   0.   ... 0.   0.   0.  ]
 [0.01 0.   0.02 ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.83 0.02 0.68 ... 0.   0.   0.34]
 [0.54 0.84 1.1  ... 0.   0.   1.99]] [[    1.      69.9 ]
 [    1.      78.92]
 [    1.     198.17]
 [    1.      49.79]
 [    1.      80.98]
 [    1.     474.69]
 [    1.      21.63]
 [    1.      26.65]
 [    1.      67.87]
 [    1.     178.36]
 [    1.      73.98]
 [    1.     237.5 ]
 [    1.      64.55]
 [    1.     779.4 ]
 [    1.      25.58]
 [    1.     142.44]
 [    1.      46.73]
 [    1.      94.44]
 [    1.     161.74]
 [    1.     217.42]
 [    1.      55.3 ]
 [    1.     187.7 ]
 [    1.      72.21]
 [    1.    1184.11]
 [    1.      23.85]
 [    1.      59.23]
 [    1.      51.14]
 [    1.     182.82]
 [    1.      80.62]
 [    1.      39.09]
 [    1.     162.01]
 [    1.     279.27]
 [    1.      70.01]
 [    1.     170.3 ]
 [    1.      26.96]
 [    1.      67.  ]
 [    1.     231.59]
 [    1.      98.48]
 [    1.     578

In [103]:
y_test = np.array(y_test).flatten()

In [104]:
y_test.shape

(500,)

In [105]:
clusters = pd.DataFrame(clustAssing, columns = ['Cluster','Dist'])


In [106]:
newC = clusters["Cluster"].astype(int)


In [107]:
print(completeness_score(y_test,newC))

0.15775237296548544


In [108]:
print(homogeneity_score(y_test,newC))

0.007790507655794082


# As can be seen above, the testing dataset had a much lower completeness and homogenity score, indicating that overall many points are not the in the same clusters and that the clusters do not all contain points of the same class.